"""Initial schema

Revision ID: b1bad1bab5bf
Revises: 
Create Date: 2026-07-22 15:56:12.996795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bad1bab5bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('credit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checking_status', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('credit_history', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('savings_status', sa.String(length=80), nullable=False),
    sa.Column('employment', sa.String(length=80), nullable=False),
    sa.Column('installment_rate', sa.Integer(), nullable=False),
    sa.Column('personal_status', sa.String(length=80), nullable=False),
    sa.Column('other_parties', sa.String(length=80), nullable=False),
    sa.Column('residence_since', sa.Integer(), nullable=False),
    sa.Column('property_magnitude', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('other_payment_plans', sa.String(length=80), nullable=False),
    sa.Column('housing', sa.String(length=80), nullable=False),
    sa.Column('existing_credits', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=80), nullable=False),
    sa.Column('num_dependents', sa.Integer(), nullable=False),
    sa.Column('own_telephone', sa.String(length=40), nullable=False),
    sa.Column('foreign_worker', sa.String(length=40), nullable=False),
    sa.Column('lr_decision', sa.String(length=20), nullable=True),
    sa.Column('lr_confidence', sa.Float(), nullable=True),
    sa.Column('lr_good_prob', sa.Float(), nullable=True),
    sa.Column('lr_bad_prob', sa.Float(), nullable=True),
    sa.Column('rf_decision', sa.String(length=20), nullable=True),
    sa.Column('rf_confidence', sa.Float(), nullable=True),
    sa.Column('rf_good_prob', sa.Float(), nullable=True),
    sa.Column('rf_bad_prob', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('consensus', sa.Boolean(), nullable=True),
    sa.Column('lr_shap_reasons', sa.Text(), nullable=True),
    sa.Column('rf_shap_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_applications_user_id'), ['user_id'], unique=False)

    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('emi', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=80), nullable=True),
    sa.Column('checking_status', sa.String(length=80), nullable=True),
    sa.Column('credit_history', sa.String(length=120), nullable=True),
    sa.Column('savings_status', sa.String(length=80), nullable=True),
    sa.Column('employment', sa.String(length=80), nullable=True),
    sa.Column('installment_rate', sa.Integer(), nullable=True),
    sa.Column('personal_status', sa.String(length=80), nullable=True),
    sa.Column('other_parties', sa.String(length=80), nullable=True),
    sa.Column('residence_since', sa.Integer(), nullable=True),
    sa.Column('property_magnitude', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('other_payment_plans', sa.String(length=80), nullable=True),
    sa.Column('housing', sa.String(length=80), nullable=True),
    sa.Column('existing_credits', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=80), nullable=True),
    sa.Column('num_dependents', sa.Integer(), nullable=True),
    sa.Column('own_telephone', sa.String(length=40), nullable=True),
    sa.Column('foreign_worker', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_user_id'), ['user_id'], unique=False)

    op.create_table('loan_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lr_decision', sa.String(length=20), nullable=True),
    sa.Column('lr_confidence', sa.Float(), nullable=True),
    sa.Column('lr_good_prob', sa.Float(), nullable=True),
    sa.Column('lr_bad_prob', sa.Float(), nullable=True),
    sa.Column('rf_decision', sa.String(length=20), nullable=True),
    sa.Column('rf_confidence', sa.Float(), nullable=True),
    sa.Column('rf_good_prob', sa.Float(), nullable=True),
    sa.Column('rf_bad_prob', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('consensus', sa.Boolean(), nullable=True),
    sa.Column('lr_shap_reasons', sa.Text(), nullable=True),
    sa.Column('rf_shap_reasons', sa.Text(), nullable=True),
    sa.Column('shap_reasons', sa.Text(), nullable=True),
    sa.Column('input_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_decisions_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_decisions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_loan_decisions_loan_id'))

    op.drop_table('loan_decisions')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_user_id'))

    op.drop_table('loan')
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_applications_user_id'))

    op.drop_table('credit_applications')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
